### ISSUE TITLE
プロジェクトに参加するように招待します

### ISSUE THREAD

**Issue by cangerjun** [suzuuuuu09/MajiToru#1]
こんばんは、鈴さん！蒼二(そうじ)です。

ここにはプロジェクトがあります。私はあなたが参加することを望んでいます。
これはGenshin ImpactとSky：Children of The Lightに関するピアノ弾くツールです。
このプロジェクトには日本語翻訳が不足しています。私はすでに日本語版のreadmeを書いていますが。
プロジェクトアドレス：specy/genshin-music/

**Comment by suzuuuuu09** [comment]
OK. I'll join.
